cask_args appdir: "/Applications"

# Taps
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "epk/epk"

# Tools
brew "wget"
brew "node"
brew "mas"
brew "tmux"
brew "dockutil"
brew "cloc"
brew "webp"
brew "go"
brew "fzf"
brew "ripgrep"
brew "postgresql"
brew "aria2"
brew "youtube-dl"

# Apps
cask "alfred"
cask "iterm2"
cask "iina"
cask "qingg"
cask "clashx"
cask "visual-studio-code"
cask "the-unarchiver"
cask "google-chrome"
cask "microsoft-teams"

# Fonts
cask "font-sf-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "betterzip"
cask "quicklook-json"
cask "qlimagesize"

# macOS App Store
mas "WeChat",    id: 836500024
mas "QQ",        id: 451108668
mas 'Numbers',   id: 409203825
mas "Keynote",   id: 409183694
