language: generic

sudo: false

os: osx

osx_image: xcode10.1

addons:
  homebrew:
    brewfile: ./install/Brewfile

script:
  - make node-packages
  - make vscode-packages

notifications:
  email: false
