cask_args appdir: "/Applications"

# Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/services"

#
brew "wget"
brew "node"
brew "yarn"
brew "mas"
brew "tmux"
brew "dockutil"
brew "cloc"
brew "webp"
brew "postgresql"

# Apps
cask "alfred"
cask "iterm2"
cask "iina"
cask "qingg"
cask "visual-studio-code"
cask "the-unarchiver"
cask "onedrive"
cask "postico"
cask "emacs"

# Fonts
cask "font-meslo-nerd-font"
cask "font-firacode-nerd-font"

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "webpquicklook"

# macOS App Store
mas "1Password", id: 443987910
mas "WeChat",    id: 836500024
mas "QQ",        id: 451108668
mas 'Numbers',   id: 409203825
mas "Keynote",   id: 409183694
mas "MindNode",  id: 1289197285
