run-shell "tmux source-file ~/.cache/wal/tmux"

# ========================
# 常规设置
# ========================

# 顶部显示
set -g status-position top
# 支持 256 色
set -g default-terminal "xterm-256color"
# 快捷键响应更快
set -sg escape-time 0
# 启用鼠标
set -g mouse on
# 窗口编号从1开始
set -g base-index 1
# 窗格编号从1开始
setw -g pane-base-index 1
# 复制模式vi风格
setw -g mode-keys vi

# ========================
# 快捷键
# ========================

# 拆分窗口
bind-key h split-window -h
bind-key v split-window -v

# 关闭面板/窗口
bind-key k kill-pane
bind-key K kill-window

# 重新加载配置
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded!"

# ========================
# 状态栏基础样式
# ========================
set -g status-interval 5
set -g status-justify left

# ========================
# 状态栏左侧
# ========================

set -g status-left-length 120
set -g status-left "#($XDG_CONFIG_HOME/tmux/scripts/status-left.sh)"

# ========================
# 状态栏右侧
# ========================

set -g status-right-length 120
set -g status-right "#($XDG_CONFIG_HOME/tmux/scripts/status-right.sh)"

# ========================
# 窗口样式
# ========================

set -g window-status-format ""
set -g window-status-current-format ""
