#!/bin/sh
#
# 添加环境模块



#######################################
# 帮助
#######################################
usage() {
cat <<EOF
Usage: ${BIN_NAME} add [package]
Available Packages:
  brew     Homebrew 安装
  git      Git 环境
  go       Golang 环境
  iterm    终端配置
  node     Node 环境
  os       系统偏好设置
  vim      NeoVim 配置
  vscode   VSCode 开发环境
  zsh      zsh 环境
  help     帮助文档
EOF
}

#######################################
# 入口
#######################################
main() {
  case $1 in
    all)
      dm add zsh
      dm add brew
      dm add go
      dm add iterm
      dm add node
      dm add vim
      dm add vscode
      dm add os
      ;;
    brew)
      sh $BIN_PATH/pkgs/brew/install.sh
      ;;
    git)
      sh $BIN_PATH/pkgs/git/install.sh
      ;;
    go)
      sh $BIN_PATH/pkgs/golang/install.sh
      ;;
    iterm)
      sh $BIN_PATH/pkgs/iterm2/install.sh
      ;;
    node)
      sh $BIN_PATH/pkgs/node/install.sh
      ;;
    os)
      sh $BIN_PATH/pkgs/os/main.sh
      ;;
    vim)
      sh $BIN_PATH/pkgs/neovim/install.sh
      ;;
    vscode)
      sh $BIN_PATH/pkgs/vscode/install.sh
      ;;
    zsh)
      sh $BIN_PATH/pkgs/zsh/install.sh
      ;;
    help)
      usage
      ;;
    *)
      echo "指定的命令无效. 请运行 dm add help."
      ;;
  esac
}

main "$@"
