#!/bin/sh
#
# 清理

source $BIN_PATH/lib/console


#######################################
# 清理 Homebrew
#######################################
brew() {
  brew cleanup --force -s > /dev/null 2>&1
  brew cask cleanup > /dev/null 2>&1
  rm -rfv /Library/Caches/Homebrew/* > /dev/null 2>&1
  brew tap --repair > /dev/null 2>&1
  brew update > /dev/null 2>&1
  brew upgrade > /dev/null 2>&1
}

#######################################
# 清理 Node
#######################################
node() {
  npm cache clean --force
  yarn cache clean --force
}

#######################################
#  清理日志
#######################################
log() {
  sudo rm -rfv /private/var/log/*  > /dev/null 2>&1
  sudo rm -rfv /Library/Logs/DiagnosticReports/* > /dev/null 2>&1
}

#######################################
#  帮助
#######################################
usage() {
cat <<EOF
Available commands:

  brew            清理 Homebrew 缓存
  node            清理 Node 缓存
EOF
}

#######################################
# 入口
#######################################
main() {
  case $1 in
    brew) brew ;;
    node) node ;;
    log) log ;;
    help) usage ;;
  esac
}

main "$@"
