#!/bin/sh
#
# 清理

source $BIN_PATH/lib/console

case $1 in
'' | 'help')
  cat <<EOF
Available commands:

  brew    清理 Homebrew 缓存
  node    清理 Node 缓存
EOF
  ;;
'brew')
  brew cleanup
  ;;
'node')
  npm cache clean --force
  yarn cache clean --force
  ;;
*)
  ;;
esac
