#!/bin/sh
#
# 配置环境

# 配置 Emacs
config_emacs() {
  source $HOME/.dotfiles/config/emacs/default.sh
}

# 配置 gitconfig
config_git() {
  source $HOME/.dotfiles/config/git/default.sh
}

# 配置 iTerm2
config_iterm() {
  source $HOME/.dotfiles/config/iterm/default.sh
}

# 配置 os
config_os() {
  source $HOME/.dotfiles/config/osx/default.sh
}

# 配置 Tmux
config_tmux() {
  source $HOME/.dotfiles/config/tmux/default.sh
}

# 配置 Vim
config_vim() {
  source $HOME/.dotfiles/config/vim/default.sh
}

# 配置 VSCode
config_vscode() {
  source $HOME/.dotfiles/config/vscode/default.sh
}

# 前端配置文件
config_web() {
  echo "web"
}

# 配置 zsh
config_zsh() {
  $HOME/.dotfiles/config/zsh/default.sh
}

case $1 in
  "" | "all")
    config_emacs
    config_git
    config_iterm
    config_os
    config_tmux
    config_vim
    config_vscode
    config_zsh
    ;;
  "emacs") config_emacs
    ;;
  "git") config_git
    ;;
  "iterm") config_iterm
    ;;
  "os") config_os
    ;;
  "tmux") config_tmux
    ;;
  "vim") config_vim
    ;;
  "vscode") config_vscode
    ;;
  "web") config_web
    ;;
  "zsh") config_zsh
    ;;
  *)
    fail ""
    ;;
esac
