#!/bin/sh
#
# 安装

case $1 in
'' | 'h' | 'help')
  cat <<EOF
Available commands:

  brew    使用 Hombrew 安装软件工具包
  code    安装 VSCode 及相关插件
  emacs   安装配置 Emacs 环境
  lsp
  vim     安装配置 NeoVim 环境
  zsh     安装配置 Zsh 环境
EOF
  ;;
*)
  if [[ ! -d "$BIN_PATH/workflow/$1" ]]; then
    echo 'The specified command is invalid. For a list of available options,run dm help.'
  else
    sh $BIN_PATH/workflow/$1/main.sh
  fi
  ;;
esac
