#!/bin/sh
#
# 移除

# 移除 Emacs
# remove_emacs() {

# }

# 移除 Vim
# remove_vim() {

# }

# 移除 zsh
# remove_zsh() {

# }

# 移除 brew
remove_brew() {
  cat $HOME/.dotfiles/packages/brew.txt | xargs -n 1 brew uninstall
}

# 移除 cask
remove_cask() {
  cat $HOME/.dotfiles/packages/cask.txt | xargs -n 1 brew cask uninstall
}

# 移除 fonts
remove_fonts() {
  cat $HOME/.dotfiles/packages/fonts.txt | xargs -n 1 brew cask uninstall
}

# 移除 mas
remove_mas() {
  cat $HOME/.dotfiles/packages/mas.txt | xargs -n 1 mas uninstall
}

# 移除 vscode 包
remove_vscode() {
  cat $HOME/.dotfiles/packages/code.txt | xargs -n 1 code --uninstall-extension
}

# 移除 node 包
remove_node() {
  cat $HOME/.dotfiles/packages/node.txt | xargs -n 1 yarn global remove
}

case $1 in
  # "emacs") remove_emacs
  #   ;;
  # "vim") remove_vim
  #   ;;
  # "zsh") remove_zsh
  #   ;;
  "brew") remove_brew
    ;;
  "cask") remove_cask
    ;;
  "fonts") remove_fonts
    ;;
  "mas") remove_mas
    ;;
  "vscode") remove_vscode
    ;;
  "node") remove_node
    ;;
  *)
    fail ""
    ;;
esac
