#!/bin/sh
#
# 卸载

source $BIN_PATH/lib/console

#######################################
# 删除 Brewfile 里的所有软件及工具
#######################################
brew() {
  /bin/bash $BIN_PATH/packages/brew/uninstall.sh
  sudo rm -rf /usr/local/Frameworks/
  sudo rm -rf /usr/local/Homebrew/
  sudo rm -rf /usr/local/bin/
  sudo rm -rf /usr/local/etc/
  sudo rm -rf /usr/local/include/
  sudo rm -rf /usr/local/lib/
  sudo rm -rf /usr/local/opt/
  sudo rm -rf /usr/local/sbin/
  sudo rm -rf /usr/local/share/
  sudo rm -rf /usr/local/var/
}

#######################################
# 删除 VSCode 环境
#######################################
# code() {
#   cat $BIN_PATH/packages/code/code.txt | xargs -n 1 code --uninstall-extensionco
#   brew uninstall visual-studio-code --cask
#   rm -rf $HOME/.vscode
#   unlink $HOME/Library/Application\ Support/Code/User/settings.json
# }

#######################################
# 删除 Emacs 环境
#######################################
emacs() {
  step "删除 Emacs 环境"
  rm -rf $HOME/.config/emacs
  brew uninstall emacs --cask
}

#######################################
# 删除 git 环境
#######################################
# git() {

# }

#######################################
# 删除 Golang 环境
#######################################
# go() {

# }

#######################################
# 删除 iTerm 环境
#######################################
# iterm() {

# }

#######################################
# 删除 Node 环境
#######################################
# node() {
#   cat $BIN_PATH/packages/node/node.txt | xargs -n 1 yarn global remove
#   brew uninstall node yarn
# }

#######################################
# 删除 postgresql 环境
#######################################
# postgresql() {

# }

#######################################
# 删除 python 环境
#######################################
# python() {

# }

#######################################
# 删除 vim 环境
#######################################
vim() {
  step "删除 vim 环境"
  rm -rf $HOME/.vim
  brew uninstall vim
}

#######################################
# 删除 Zsh 环境
#######################################
# zsh() {
#   rm -rf $HOME/.oh-my-zsh
#   rm -rf $HOME/.zshrc
# }

#######################################
# 帮助
#######################################
usage() {
cat <<EOF
Available commands:

  brew            删除 Homebrew 环境
  code            删除 VSCode 环境
  emacs           删除 Emacs 环境
  git             删除 git 配置
  go              删除 Golang 环境
  iterm           删除 iTerm2 环境
  node            删除 Node 环境
  postgresql      删除 postgresql 环境
  python          删除 Python 环境
  vim             删除 Vim 环境
  zsh             删除 Zsh 配置
  reset           重置系统
EOF
}



#######################################
# 入口
#######################################
main() {
  case $1 in
    brew)
      brew
      ;;
    code)
      code
      ;;
    emacs)
      emacs
      ;;
    git)
      git
      ;;
    go)
      go
      ;;
    iterm)
      iterm
      ;;
    node)
      node
      ;;
    postgresql)
      postgresql
      ;;
    python)
      python
      ;;
    vim)
      vim
      ;;
    zsh)
      zsh
      ;;
    help)
      usage
      ;;
  esac
}

main "$@"
