#!/bin/sh
#
# 输出开头信息

source $HOME/.dotfiles/lib/foundation

echo ""
echo "           ${YELLOW}|${RESET}"
echo "         ${YELLOW}\ _ /${RESET}"
echo "       ${YELLOW}-= (_) =-${RESET}"
echo "         ${YELLOW}/   \\${RESET}         ${GREEN}_\/_${RESET}"
echo "           ${YELLOW}|${RESET}           ${GREEN}//o\  _\/_${RESET}"
echo "    ${CYAN}_____ _ __ __ ____ _${RESET} ${GREEN}|${RESET} ${CYAN}__${RESET}${GREEN}/o\\\\\ ${RESET}${CYAN}_${RESET}"
echo "  ${CYAN}=-=-_-__=_-= _=_=-=_ -${RESET} ${GREEN}|${RESET}${CYAN}_=-=${RESET}${GREEN}|${RESET}${CYAN}- _${CYAN}"
echo "   ${CYAN}=- _=-=- -_=-=_ -${RESET}          ${GREEN}|${RESET}"
echo "     ${CYAN}=- =- -=.--${RESET}"
echo ""
echo "${GREEN}AUTHOR${RESET} : Chunhui Ren"
echo "${GREEN}GITHUB${RESET} : https://github.com/renchunhui/dotfiles"
echo ""
echo "${YELLOW}NOTE${RESET}   :"
