#!/bin/sh
#
# Colors and formatting

RESET=$'\e[0m'
RESET_BOLD=$'\e[21m'
RESET_DIM=$'\e[22m'

BOLD=$'\e[1m'
DIM=$'\e[2m'
UNDERLINED=$'\e[4m'

RED=$'\e[31m'
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
BLUE=$'\e[34'
PURPLE=$'\e[35'
CYAN=$'\e[36m'
LIGHT_GRAY=$'\e[37m'
