#!/bin/sh
#
# 环境检测

homebrew() {
  if test ! $(which brew); then
    /bin/bash $BIN_PATH/lib/brew_install
  fi
}

code() {
  homebrew
  if test ! $(which code); then
    brew cask install visual-studio-code
  fi
}

yarn() {
  homebrew
  if test ! $(which yarn); then
    brew install yarn
  fi
}
