source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/Keywords.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/variables.conf


# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}


source = ~/.config/hypr/conf/binds.conf

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
