#!/bin/sh

#######################################
# 帮助
#######################################
usage() {
cat <<EOF
Usage:
  dot uninstall [command]

Available Commands:
  brew     Homebrew 安装
  git      Git 环境
  golang   Golang 环境
  kitty    终端配置
  node     Node 环境
  os       系统偏好设置
  neovim   NeoVim 配置
  vscode   VSCode 开发环境
  zsh      zsh 环境
  help     帮助文档
EOF
}


#######################################
# 入口
#######################################
main() {
  if [[ $1 == "all" ]]; then
    dot uninstall zsh
    dot uninstall brew
    dot uninstall golang
    dot uninstall kitty
    dot uninstall neovim
    dot uninstall node
    dot uninstall postgresql
    dot uninstall vscode
  elif [[ $1 == "help" ]]; then
    usage
  else
    sh $DOTPATH/internal/$1/uninstall.sh
  fi
}

main "$@"
