cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/core"

tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap 'd12frosted/emacs-plus'

brew "mas"
brew "wget"
brew "node"
brew "yarn"
brew "tmux"
brew "neovim"
brew "aria2"
brew "go"
brew "dockutil"
# brew "emacs", args: ["with-cocoa","srgb"]

cask "alfred"
cask "iterm2"
cask "google-chrome"
cask "hammerspoon"
cask "qq"
cask "iina"
cask "visual-studio-code"
cask "shadowsocksx-ng"
cask "sketch"
cask "the-unarchiver"
cask "postman"
cask "qingg"
cask "docker"
cask "dropbox"

# Quick Look Plugins 
# 参考: https://github.com/sindresorhus/quick-look-plugins
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'betterzip'
cask 'qlimagesize'
cask 'webpquicklook'

# mas 'Xcode', id: 497799835
mas 'WeChat', id: 836500024
# mas 'Pages', id: 409201541
# mas 'Numbers', id: 409203825