# Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# Binaries
brew "wget"
brew "node"
brew "yarn"
brew "tmux"
brew "dockutil"
brew "cloc"
brew "webp"
brew "postgresql"

# Apps
cask "alfred"
cask "iterm2"
cask "iina"
cask "qingg"
cask "google-chrome"
cask "visual-studio-code"
cask "the-unarchiver"
cask "onedrive"
cask "recordit"
cask "navicat-for-postgresql"

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "webpquicklook"

# Fonts
cask "font-meslo-nerd-font"

# App Store
mas "WeChat",          id: 836500024
mas "QQ",              id: 451108668
mas "Microsoft Word",  id: 462054704
mas "Microsoft Excel", id: 462058435
mas "Keynote",         id: 409183694
