#!/bin/sh
#
# 方法

#######################################
# 读取行内容
#######################################
read_line() {
  str=$1

  if [[ "${str:0:1}" == "#" || ${#str} == 0 ]]; then
    continue
  fi
}

#######################################
# 检查包是否有安装过
#######################################
check_pkg() {
  eval "$1 $2" > /dev/null

  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    info "$1 $2"
    eval "$1 $2"

    if [[ $? != 0 ]]; then
      error "failed to install $2! aborting..."
    fi
    ok "${BOLD} $2 ${RESET_BOLD}${DIM}is already installed.${RESET_DIM}"
  else
    ok "${BOLD} $2 ${RESET_BOLD}${DIM}is already installed.${RESET_DIM}"
  fi
}
