#!/bin/sh
#
# 信息打印

BLACK=$'\e[30m'
RED=$'\e[31m'
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
BLUE=$'\e[34'
MAGENTA=$'\e[95m'
CYAN=$'\e[36m'
WHITE=$'\e[97m'

RESET=$'\e[0m'
RESET_BOLD=$'\e[21m'
RESET_DIM=$'\e[22m'

ICON_ASK='?'
ICON_INFO='➜'
ICON_OK='✔'
ICON_WARN='⚠'
ICON_FAIL='✖'
ICON_ARROR_RIGHT="❯"
ICON_STEP='⧗'

# 信息
info() {
  echo ${CYAN}${ICON_INFO}${RESET} $1
}

# 正确
ok() {
  echo ${GREEN}${ICON_OK}${RESET} $1
}

# 警告
warn() {
  echo ${YELLOW}${ICON_WARN}${RESET} $1
}

# 错误
fail() {
  echo ${RED}${ICON_FAIL}${RESET} $1
}
