# 配置文件

# 外观
# ==========================================
Appearance:
  # 主题
  - theme: 0
  # 文件图标
  - fileIcon: 0

# 快捷键
# ==========================================
Keymap: 0

# 常规设置
# ==========================================
General:
  # 常规
  - encoding=utf-8                        # 编码
  - mouse=                                # 禁用鼠标
  - termguicolors
  - shell=/bin/zsh                        # 将 Shell 设置成 zsh
  - fileformats=unix,dos,mac
  - wildmenu                              # vim 自身命令行模式智能补全
  # 缩进
  - textwidth=80                          # 文本宽度最大字符数
  - noexpandtab
  - tabstop=2
  - shiftwidth=2
  - smarttab
  - autoindent
  - smartindent
  - shiftround
  # 搜索
  - ignorecase
  - smartcase
  - infercase
  - hlsearch
  - wrapscan
  - showmatch
  - matchpairs+=<:>
  - matchtime=1
  - cpoptions-=m
  # 外观
  - noshowmode
  - shortmess=aoOTI
  - scrolloff=2
  - sidescrolloff=5
  - number                                # 显示行号
  - noruler
  - list

  - showtabline=2
  - winwidth=30
  - winheight=1
  - pumheight=15
  - helpheight=12
  - previewheight=12

  - noshowcmd
  - cmdheight=2
  - cmdwinheight=5
  - noequalalways
  - laststatus=2
  - colorcolumn=80
  - display=lastline

# 插件开关
# ==========================================
Switch:
  - icon: 0
  - html: 0
  - css: 0
  - javascript: 0
  - typescript: 0
  - json: 0

# 插件列表
# ==========================================
Plugins:
  - { repo: scrooloose/nerdtree }
  - { repo: tiagofumo/vim-nerdtree-syntax-highlight}
  - { repo: Xuyuanp/nerdtree-git-plugin}
  - { repo: kien/ctrlp.vim}
  - { repo: editorconfig/editorconfig-vim}

  - { repo: vim-airline/vim-airline}
  - { repo: ryanoasis/vim-devicons}
  - { repo: joshdick/onedark.vim}

  - { repo: othree/html5.vim}

  - { repo: cakebaker/scss-syntax.vim, options: "'for': 'scss'" }
  - { repo: othree/yajs.vim,           options: "'for': 'javascript'" }
  - { repo: othree/javascript-libraries-syntax.vim}
  - { repo: pangloss/vim-javascript,   options: "'for': 'javascript'" }

  - { repo: othree/jsdoc-syntax.vim }
  - { repo: ternjs/tern_for_vim }
