name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Repository
        run: git clone https://github.com/renchunhui/dotfiles ~/.config/dotfiles -b develop

      - name: Make install.sh executable
        run: cd ~/.config/dotfiles && chmod +x install.sh

      - name: Run install.sh
        run: ./install.sh
